### ISSUE TITLE
TODO?

### ISSUE THREAD

**Issue by SergioCrisostomo** [tiagomoraismorgado/estatisticasincendiosportugal#1]
Hi,

I suggest you guys make a TODO/Roadmap list of things you need help with. This would make it easier for people to jump into tasks without loosing too much time before getting engaged.

(feel free to close this when read)

:/ escrevi em Inglês, dei-me conta agora :)

**Comment by tiagomoraismorgado** [comment]
**it's already done. you can find it here https://github.com/tiagomoraismorgado/estatisticasincendiosportugal/projects**

---

**já se encontra feito. pode ser encontrado aqui https://github.com/tiagomoraismorgado/estatisticasincendiosportugal/projects**
